POST {{host}}/auth/signUp
Content-Type: application/json

{
  "application": {
    "build": "string",
    "bundleID": "string",
    "version": "string"
  },
  "device": {
    "deviceName": "string",
    "modelName": "string",
    "nameOS": "android",
    "versionOS": "string"
  },
  "email": "user@example.com",
  "name": "string",
  "password": "string"
}
