POST {{host}}/auth/signIn
Content-Type: application/json
Authorization: {{authToken}}

{
  "application": {
    "build": "string",
    "bundleID": "string",
    "version": "string"
  },
  "device": {
    "deviceName": "string",
    "modelName": "string",
    "nameOS": "android",
    "versionOS": "string"
  },
  "token": ""
}
