###


###
PATCH http://localhost/account?
    Body={{$placeholder}}
    Content-Type: application/json

###
POST http://localhost/account?
    Body={{$placeholder}}
    Content-Type: application/json

###
DELETE http://localhost/accountGroup?
    id={{$placeholder}}

###
GET http://localhost/accountGroup?
    accountGroupIDs={{$placeholder}}

###
PATCH http://localhost/accountGroup?
    Body={{$placeholder}}
    Content-Type: application/json

###
POST http://localhost/accountGroup?
    Body={{$placeholder}}
    Content-Type: application/json

###
POST http://localhost/auth/refreshTokens?
    Dody={{$placeholder}}
    Content-Type: application/json

###
POST http://localhost/auth/signIn?
    Body={{$placeholder}}
    Content-Type: application/json

###
POST http://localhost/auth/signOut
Content-Type: application/json

###
POST http://localhost/auth/signUp?
    Body={{$placeholder}}
    Content-Type: application/json

###
GET http://localhost/settings/currencies

###
GET http://localhost/settings/icons

###
POST http://localhost/settings/sendNotification?
    Body={{$placeholder}}

###
POST http://localhost/settings/updateCurrencies

###
GET http://localhost/settings/version/

###
DELETE http://localhost/tag?
    id={{$placeholder}}

###
GET http://localhost/tag?
    accountGroupIDs={{$placeholder}}

###
PATCH http://localhost/tag?
    Body={{$placeholder}}
    Content-Type: application/json

###
POST http://localhost/tag?
    Body={{$placeholder}}
    Content-Type: application/json

###
GET http://localhost/tag/to_transactions?
    Body={{$placeholder}}
    Content-Type: application/json

###
DELETE http://localhost/transaction?
    id={{$placeholder}}

###
GET http://localhost/transaction?
    accountGroupIDs={{$placeholder}}&
    accountID={{$placeholder}}&
    dateFrom={{$placeholder}}&
    dateTo={{$placeholder}}&
    limit={{$placeholder}}&
    offset={{$placeholder}}&
    type={{$placeholder}}

###
PATCH http://localhost/transaction?
    Body={{$placeholder}}
    Content-Type: application/json

###
POST http://localhost/transaction?
    Body={{$placeholder}}
    Content-Type: application/json

###
GET http://localhost/user

###
PATCH http://localhost/user?
    Body={{$placeholder}}
    Content-Type: application/json
