// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
  "fmt"
  "os"

  "github.com/mailru/easyjson/gen"

  pkg "pkg/log"
)

func main() {
  g := gen.NewGenerator("jsonHandler_easyjson.go")
  g.SetPkg("log", "pkg/log")
  g.Add(pkg.EasyJSON_exporter_jsonLog(nil))
  if err := g.Run(os.Stdout); err != nil {
    fmt.Fprintln(os.Stderr, err)
    os.Exit(1)
  }
}
