// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  log

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( jsonLog ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* jsonLog ) UnmarshalJSON([]byte) error { return nil }
func ( jsonLog ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* jsonLog ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_jsonLog *jsonLog
