PATCH {{host}}/account
Authorization: {{authToken}}
Content-Type: application/json

{
  "id": 0,
  "accountingInCharts": null,
  "accountingInHeader": null,
  "budget": {
    "amount": null,
    "daysOffset": null,
    "fixedSum": null,
    "gradualFilling": null
  },
  "currencyCode": null,
  "iconID": null,
  "name": null,
  "parentAccountID": null,
  "remainder": null,
  "serialNumber": null,
  "visible": null
}
