name: dev deploy

on:
  push:
    branches:
      - release/*
      - hotfix/*

jobs:
  general-deploy-pipeline:
    uses: finfix/devops/.github/workflows/reusable-deploy.yml@main
    with:
      image_name: ${{ github.repository }}-dev
      make_command: deploy-coin-server-dev
      devops_repository: finfix/devops
    secrets: inherit
