name: prod deploy

on:
  push:
    tags:
      - v*
    paths:
      - 'server/**'

jobs:
  general-deploy-pipeline:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      image_name: ${{ github.repository }}
      ansible_playbook_filename: deploy-go-server.yml
      devops_repository: finfix/devops
    secrets: inherit
