name: prod deploy

on:
  push:
    tags:
      - v*
    paths:
      - 'server/**'

jobs:
  general-deploy-pipeline:
    uses: finfix/devops/.github/workflows/reusable-deploy.yml@main
    with:
      image_name: ${{ github.repository }}
      make_command: deploy-coin-server
      devops_repository: finfix/devops
    secrets: inherit
